# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'FacebookCore'
pod 'FacebookLogin'

target 'MiBodyiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiBodyiOS

  target 'MiBodyiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiBodyiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
