# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiBodyiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiBodyiOS
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Pageboy', '~> 2.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'SDWebImage/GIF'
  pod 'SwiftyJSON'
  pod 'ISHPullUp'
  pod 'FSPagerView'
#  pod 'KDDragAndDropCollectionViews', '~> 1.0'

end
